version: '3.7'
services:
    mysqldb:
        image: mysql:5.7
        restart: on-failure
        # volumes:
        # - db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - "MYSQL_DATABASE=database"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=user"
            - "MYSQL_ROOT_PASSWORD=root"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - './app/:/usr/src/app'
        environment: 
            DATABASE_URL: mysql://user:user@mysqldb:3306/database?serverVersion=5.7
        # user: ${LOCAL_USER}  

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'    
        depends_on:
            - php